BaseURL= "https://coderarena.com.br/"
LanguageCode= "pt-br"
DefaultContentLanguage = "pt-br"
Title = "Coder Arena"
weight = 1
Copyright = "Creative Commons - 2020"
enableRobotsTXT = true
disqusShortname = "coderarena"
googleAnalytics = "UA-167342890-1"
pluralizeListTitles = false
enableemoji = false
summaryLength = 40

theme = "ramium"

[auhor]
  name = "Marcos V. Leal"

[permalinks]
  posts = "/blog/:slug/"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.8

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    weight = 2
      [[menu.main]]
        parent = "blog"
        name = "Artigos"
        url = "/posts/"
        weight = 1
      [[menu.main]]
        parent = "blog"
        name = "Tags"
        url = "/tags/"
        weight = 2
      [[menu.main]]
        parent = "blog"
        name = "Sessões"
        url = "/sections/"
        weight = 3

  [[menu.main]]
    name = "Autor"
    url = "/author/"
    weight = 3

[params]
  googleSearch = "005027135246943188782:x3jveffk7tj"
  showDate = true # make false if dont want to show date for evergeen articles
  cdnURL = "https://cdn.coderarena.com.br"

  tagsInHome = 40     # set zero to not show in home page
  sectionsInHome = 5  # set zero to not show in home page
  paginatePostsPerPage = 5
  paginateTagsPerPage = 6

  description = "Artigos e vídeo-aulas sobre desenvolvimento, programação, carreira, empreendedorismo e outras coisas."
  metadescription = "Artigos e vídeo-aulas sobre desenvolvimento, programação, carreira, empreendedorismo e outras coisas."
  logo = "images/logo.svg"
  cover = "images/coderarena-cover.png"
  author = "Marcos V. Leal"
  authorimage = "images/author-marcosvleal.png"
  authorlocation = "São Paulo, Brasil"
  authorwebsite = "https://coderarena.com.br"
  email = "marcosleal@coderarena.com.br"
  bio= "Escritor de códigos, apaixonado por café, tecnologia e empreendedorismo."
  paginate = 10

  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubProfile = "marcosleal-prd"
  twitterProfile = "marcosleal_prd"
  facebookProfile = "marcosleal.prd"
  instagramProfile = "coderarena"
  linkedinProfile = "marcosleal-prd"
  youtubeChannel = "UC9ljALQ1KcfatYfoo_MqSgQ"

  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "dracula"

  [params.social]
    twitter = "marcosleal_prd"

[taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
  unsafe = true

[deployment]
order = [".png$", ".jpg$", ".gif$", ".svg$"]

[[deployment.targets]]
name = "s3"
URL = "s3://coderarena.com.br?region=us-east-1"
cloudFrontDistributionID = "E3PYZWZDWHZZ50"

[[deployment.matchers]]
pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
