BaseUrl= "https://coderarena.com.br/"
LanguageCode= "pt-br"
DefaultContentLanguage = "pt-br"
Title = "Coder Arena"
weight = 1
Copyright = "Creative Commons - 2020"
canonifyURLs = true
enableRobotsTXT = true
disqusShortname = "coderarena"

theme = "paper"

[auhor]
  name = "Marcos V. Leal"

[permalinks]
  posts = "/posts/:slug/"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.8

[menu]
  [[menu.main]]
    identifier = "about"
    name = "Sobre"
    url = "/about/"
    weight = -130

[params]
  description = "Artigos e vídeo-aulas sobre desenvolvimento, programação, carreira, empreendedorismo e outras coisas."
  metadescription = "Artigos e vídeo-aulas sobre desenvolvimento, programação, carreira, empreendedorismo e outras coisas."
  cover = "images/2020/05/coderarena-header.png"
  author = "Marcos V. Leal"
  email = "marcosleal@coderarena.com.br"
  authorlocation = "São Paulo, Brasil"
  authorwebsite = "https://coderarena.com.br"
  bio= "Escritor de códigos, apaixonado por café, tecnologia e empreendedorismo."
  logo = "images/2020/05/logo-icon.png"
  paginate = 10

  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "marcosleal-prd"
  twitterName = "marcosleal_prd"
  facebookName = "marcosleal.prd"
  instagramName = "marcosleal.prd"
  linkedinName = "marcosleal-prd"

  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "dracula"

  [params.social]
    twitter = "marcosleal_prd"

[deployment]
order = [".png$", ".jpg$", ".gif$", ".svg$"]

[[deployment.targets]]
name = "s3"
URL = "s3://coderarena.com.br?region=us-east-1"
cloudFrontDistributionID = "E3PYZWZDWHZZ50"

[[deployment.matchers]]
pattern = "^.+\\.(js|css|png|jpg|gif|svg|ttf)$"
cacheControl = "max-age=630720000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
