baseURL= "https://coderarena.com.br/"
languageCode= "pt-br"
defaultContentLanguage = "pt-br"
title = "Coder Arena"
enableRobotsTXT = true
disqusShortname = "coderarena"
googleAnalytics = "UA-167342890-1"
pluralizeListTitles = false
enableEmoji = true
summaryLength = 40

theme = "ramium"

[permalinks]
  posts = "/posts/:slug/"
  wiki = "/wiki/:slug/"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Artigos"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "wiki"
    name = "Wiki"
    url = "/wiki/"
    weight = 3

  [[menu.main]]
    name = "Newsletter"
    url = "https://news.coderarena.com.br/"
    weight = 4

[params]
  googleSearch = "005027135246943188782:x3jveffk7tj"
  showDate = true

  tagsInHome = 40
  sectionsInHome = 5
  paginate = 10
  paginateTagsPerPage = 6
  paginatePostsPerPage = 5

  description = "Artigos e vídeo-aulas sobre desenvolvimento, programação, carreira, empreendedorismo e outras coisas."
  metadescription = "Artigos e vídeo-aulas sobre desenvolvimento, programação, carreira, empreendedorismo e outras coisas."
  logo = "/images/logo.svg"
  images = ["/images/coder-arena.jpg"]
  author = "Marcos V. Leal"
  email = "marcosleal@coderarena.com.br"

  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  twitterProfile = "marcosleal_prd"
  facebookProfile = "marcosleal.prd"
  linkedinProfile = "marcosleal-prd"
  githubProfile = "coder-arena"
  instagramProfile = "coderarena"
  youtubeChannel = "UC9ljALQ1KcfatYfoo_MqSgQ"

  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    [markup.highlight]
      lineNos = false
      lineNumbersInTable = false
      tabWidth = 2
      style = "dracula"
