[build]
publish = "public"
command = "hugo --theme=ramium"

[context.production.environment]
HUGO_VERSION = "0.69.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.69.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.69.2"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.69.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://coderarena.netlify.app"
  to = "https://coderarena.com.br/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404
  force = true

[[redirects]]
  from = "/vip"
  to = "https://news.coderarena.com.br/"
  status = 200
  force = true
